parallel -n 5 -j 5 python3.8 -- \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Scalefree5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Hierarchy5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Modular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Smallworld5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Random5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5RealNetwork5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular1 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular2 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular3 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular4 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular5 -f celegans_random_hyperparam_sr05 \
/home/wehak/code/reservoirpy/deepCA/hyper_param_random_seach_batch.py -i SR_0.5Regular5 -f celegans_random_hyperparam_sr05 \